'use client';
import { useEffect, useState } from 'react';
import { Download, FileCheck2, RefreshCw, ArrowUpRight, ChevronDown, Printer, ShieldCheck } from 'lucide-react';
import { api, Detail, Dimension, Proposal, Score, Assumption, Assessment, Evidence } from '../lib/types';
import { Field } from './workbench-forms';
import { readableWarning } from '../lib/readable-reply';

type Run = (action: () => Promise<void>, success?: string) => Promise<void>;
function initialProposal(dimensions: Dimension[]): Proposal {
  return { dimensions: Object.fromEntries(dimensions.map(d => [d.key, { score: null, reason: '', basis: 'assumption', evidence_ids: [] }])),
    assumptions: ['目标客户或使用者确实存在需求', '收入或业务价值可以兑现', '关键人员与资源可以获得', '交付过程和合规条件可行'].map((claim, i) => ({ id: 'P0-0' + (i + 1), claim, evidence_ids: [], validation_method: '', pass_threshold: '', fail_threshold: '' })),
    pros: [], cons: [], policy_caps: [], vetoes: [], s_conditions: { repeatable: false, resources_available: false, portfolio_feasible: false, review_complete: false } };
}

function ReferenceSelect({ ids, evidence, onChange }: { ids: string[]; evidence: Evidence[]; onChange: (ids: string[]) => void }) {
  return <select aria-label="关联证据" multiple value={ids} onChange={e => onChange(Array.from(e.target.selectedOptions).map(o => o.value))} size={Math.min(3, Math.max(1, evidence.length))}>{evidence.length ? evidence.map(e => <option key={e.id} value={e.id}>{e.title} · E{e.level}</option>) : <option disabled>暂无证据，可先保留为假设</option>}</select>;
}

function EvidenceReferences({ ids, evidence }: { ids: string[]; evidence: Evidence[] }) {
  if (!ids.length) return <p className="source-location">未关联证据；依据来自项目陈述或假设，需进一步核验。</p>;
  return <div className="report-references">{ids.map(id => {
    const item = evidence.find(e => e.id === id);
    if (!item) return <p className="source-location" key={id}>引用的资料未包含在本次快照中，请复核引用。</p>;
    return <details key={id}><summary>{item.title}</summary><div className="evidence-content"><p className="source-location">来源：{item.source_locator || '未记录'}<br />数据期间：{item.data_period || '未记录'}<br />采集时间：{item.retrieved_at || '未记录'}<br />适用范围 / 口径：{item.scope || '未记录'}<br />核验状态：{item.verification_status === 'verified' ? '已核验' : '未核验'} · 登记等级：E{item.level}<br />有效至：{item.valid_until || '未设定'}{item.conflict && ' · 存在待解释冲突'}</p><pre>{item.content || '未保存正文'}</pre></div></details>;
  })}</div>;
}

export function ReportPanel({ detail, dimensions, busy, run, refresh }: { detail: Detail; dimensions: Dimension[]; busy: boolean; run: Run; refresh: () => Promise<void> }) {
  const [proposal, setProposal] = useState<Proposal>(detail.project.proposal || initialProposal(dimensions));
  const [selected, setSelected] = useState<Assessment | null>(detail.assessments[0] || null);
  const [confirmed, setConfirmed] = useState(false);
  const [edit, setEdit] = useState(false);
  useEffect(() => { setConfirmed(false); }, [proposal]);
  useEffect(() => { setSelected(detail.assessments[0] || null); }, [detail.assessments]);
  useEffect(() => { setProposal(detail.project.proposal || initialProposal(dimensions)); }, [detail.project.proposal, dimensions]);
  function setDimension(key: string, patch: Partial<Score>) { setConfirmed(false); setProposal(p => ({ ...p, dimensions: { ...p.dimensions, [key]: { ...p.dimensions[key], ...patch } } })); }
  function setAssumption(index: number, patch: Partial<Assumption>) { setConfirmed(false); setProposal(p => ({ ...p, assumptions: p.assumptions.map((a, i) => i === index ? { ...a, ...patch } : a) })); }
  async function evaluate(manual = false) {
    await run(async () => { const record = await api<Assessment>('/projects/' + detail.project.id + '/assess', 'POST', manual ? { proposal, confirmed } : {}); setSelected(record); await refresh(); if (record.result.grade !== 'NR') setEdit(false); }, '本次评估已保存，历史结果不会被覆盖');
  }
  const r = selected?.result;
  const pendingFacts = Object.entries(detail.project.pending_patch || {}).some(([key, value]) => detail.project[key] !== value);
  return <section className="report-area"><div className="section-heading"><div><h2>评级报告</h2><p>每个结论都绑定当时的公司资料、项目事实和证据。</p></div><div className="button-group">{selected && <><button className="secondary" onClick={() => window.print()}><Printer size={15} />打印</button><a className="secondary" href={'/api/assessments/' + selected.id + '/export'}><Download size={15} />导出快照</a></>}<button className="primary" disabled={busy} onClick={() => { if (detail.project.proposal) setEdit(true); else evaluate(); }}><RefreshCw size={15} />{selected ? '重新评估' : '检查评级条件'}</button></div></div>
    {pendingFacts && <p className="review-note" role="status">模型整理了新的项目事实。请先到“项目资料”核对并保存，再生成本次评级。</p>}
    {detail.assessments.length > 1 && <label className="history-select">历史评估<select value={selected?.id || ''} onChange={e => setSelected(detail.assessments.find(a => a.id === e.target.value) || null)}>{detail.assessments.map((a, i) => <option key={a.id} value={a.id}>{new Date(a.created_at).toLocaleString('zh-CN')} · {a.result.grade}{i === 0 ? ' · 最新' : ''}</option>)}</select></label>}
    {!r ? <div className="report-empty"><FileCheck2 size={35} /><h3>先完成事实与证据，再形成结论。</h3><p>可以检查当前资料缺口。连接模型后，在项目访谈中生成评分建议，再到这里核对。</p></div> : <article className="rating-document">
      <div className="rating-summary"><div className={'final-grade grade-' + r.grade}>{r.grade}</div><div className="rating-summary-text"><h2>{r.action}</h2><p>{r.status} · 判断置信度：{r.confidence}</p><span>评估于 {new Date(selected!.created_at).toLocaleString('zh-CN')} · 公司基线 v{String(selected!.snapshot.company.version || '未建立')}</span></div>{r.base_score !== null && <div className="rating-score"><strong>{r.base_score}<span>/100</span></strong><small>业务分 · {r.evidence_level} 证据</small></div>}</div>
      {r.grade === 'NR' ? <section className="report-section"><h3>补齐这些信息后，再判断</h3><p>当前依据还不足。这不表示项目不好，也不形成投入建议。</p><ul className="missing-list">{r.missing.map((m, i) => <li key={i}><span />{m}</li>)}</ul>{r.validation_plan?.length > 0 && <><h3>现在可以执行的补证任务</h3>{r.validation_plan.map((v, i) => <div className="validation-item" key={i}><h4>{v.claim}</h4><p>{v.method}</p><p>通过：{v.pass}</p><p>停止 / 调整：{v.fail}</p></div>)}</>}</section> : <>
        <section className="report-section"><div className="section-heading"><h3>八维业务判断</h3><span className="footnote">业务质量与证据强度分开计算</span></div><div className="dimension-results">{r.dimensions.map(d => <div className="dimension-result" key={d.key}><div><strong>{d.name}</strong><span>{d.weighted} / {d.weight}</span></div><div className="score-track"><span style={{ width: `${Number(d.score) / 5 * 100}%` }} /></div><p><strong>{d.basis === "fact" ? "事实判断" : d.basis === "unknown" ? "未知" : "假设 / 推断"}：</strong>{d.reason}</p><EvidenceReferences ids={d.evidence_ids} evidence={selected!.snapshot.evidence} /></div>)}</div></section>
        <section className="report-section"><h3>影响最终评级的规则</h3><ul className="rule-list">{r.triggered_rules.map((rule, i) => <li key={i}><ShieldCheck size={16} />{rule}</li>)}</ul>{!!r.warnings.length && <div className="review-note">{r.warnings.map((w, i) => <p key={i}>{readableWarning(w, selected!.snapshot.evidence)}</p>)}</div>}</section>
        <section className="report-section argument-columns"><div><h3>支持投入的理由</h3><ol>{r.pros.map((p, i) => <li key={i}>{p}</li>)}</ol></div><div><h3>必须认真面对的反对理由</h3><ol>{r.cons.map((p, i) => <li key={i}>{p}</li>)}</ol></div></section>
        <section className="report-section"><h3>关键假设与证据</h3>{r.assumptions.map(a => <div className="assumption-result" key={a.id}><span className="evidence-level">{a.level}</span><div><strong>{a.claim}</strong><EvidenceReferences ids={a.evidence_ids} evidence={selected!.snapshot.evidence} /></div></div>)}</section>
        <section className="report-section"><h3>下一步投入与验证</h3><div className="resource-summary"><div><span>当前资源上限</span><strong>¥{r.resource_plan.available_limit?.toLocaleString('zh-CN')}</strong><small>{r.resource_plan.formula}</small></div><div><span>本次投入建议</span><strong>{r.resource_plan.proposed_budget == null ? '需进一步核定' : '¥' + r.resource_plan.proposed_budget.toLocaleString('zh-CN')}</strong><small>{r.resource_plan.note}</small></div></div>{r.validation_plan.map((v, i) => <div className="validation-item" key={i}><h4>{v.claim}</h4><p>{v.method}</p><div><span>通过：{v.pass}</span><span>停止 / 调整：{v.fail}</span></div></div>)}</section>
        <section className="report-section"><h3>何时回来重新评估</h3><ul>{r.reassessment_triggers.map((t, i) => <li key={i}>{t}</li>)}</ul></section>
      </>}
      <div className="report-meta">规则版本 {r.rule_version} · 证据与输入已保存快照 · 置信度不是项目成功概率</div>
    </article>}
    <div className="manual-review-heading"><div><h3>{detail.project.proposal ? '核对当前评分建议' : '需要人工评审？'}</h3><p>{detail.project.proposal ? '逐项检查依据，确认后由规则引擎计算等级。' : '可由评审人员填写八维判断与关键假设。系统不会将人工填写伪装成模型分析。'}</p></div><button className="secondary" onClick={() => setEdit(!edit)}>{edit ? '收起评审表' : '打开评审表'}<ChevronDown size={16} /></button></div>
    {edit && <form className="form-document manual-review" onSubmit={e => { e.preventDefault(); evaluate(true); }}><section className="form-section"><h3>八维判断</h3><p className="section-description">未知保持空白；低于3分需要已知负面事实，不能因为缺证据直接扣低业务分。</p>{dimensions.map(d => { const v = proposal.dimensions[d.key] || { score: null, reason: '', basis: 'unknown', evidence_ids: [] }; return <fieldset className="score-editor" key={d.key}><legend>{d.name}<span>权重 {d.weight}%</span></legend><div className="score-inputs"><Field label="业务原始分"><select value={v.score ?? ''} onChange={e => setDimension(d.key, { score: e.target.value === '' ? null : Number(e.target.value) })}><option value="">未知 / 无法判断</option>{Array.from({ length: 11 }, (_, i) => i / 2).map(n => <option key={n} value={n}>{n} / 5</option>)}</select></Field><Field label="判断性质"><select value={v.basis} onChange={e => setDimension(d.key, { basis: e.target.value })}><option value="assumption">假设或推断</option><option value="fact">已知事实</option><option value="unknown">未知</option></select></Field><Field label="关联证据"><ReferenceSelect evidence={detail.evidence} ids={v.evidence_ids} onChange={evidence_ids => setDimension(d.key, { evidence_ids })} /></Field></div><Field label="具体依据"><textarea rows={2} value={v.reason} onChange={e => setDimension(d.key, { reason: e.target.value })} placeholder="说明为什么给这个分数，区分事实、推断和未知。" /></Field></fieldset>; })}</section>
      <section className="form-section"><div className="section-heading"><h3>决定项目成立的关键假设</h3><button type="button" className="secondary" onClick={() => setProposal(p => ({ ...p, assumptions: [...p.assumptions, { id: "P0-" + crypto.randomUUID().slice(0, 8), claim: "", evidence_ids: [], validation_method: "", pass_threshold: "", fail_threshold: "" }] }))}>添加关键假设</button></div>{proposal.assumptions.map((a, i) => <fieldset className="assumption-editor" key={a.id}><legend>关键假设 {i + 1}</legend><button type="button" className="secondary" disabled={proposal.assumptions.length <= 1} onClick={() => setProposal(p => ({ ...p, assumptions: p.assumptions.filter((_, index) => index !== i) }))}>移除此假设</button><Field label="假设内容"><input value={a.claim} onChange={e => setAssumption(i, { claim: e.target.value })} /></Field><Field label="支持这个假设的证据"><ReferenceSelect ids={a.evidence_ids} evidence={detail.evidence} onChange={ids => setAssumption(i, { evidence_ids: ids })} /></Field><div className="form-grid"><Field label="验证方式"><input value={a.validation_method || ''} onChange={e => setAssumption(i, { validation_method: e.target.value })} /></Field><Field label="通过阈值"><input value={a.pass_threshold || ''} onChange={e => setAssumption(i, { pass_threshold: e.target.value })} /></Field><Field label="失败与止损阈值"><input value={a.fail_threshold || ''} onChange={e => setAssumption(i, { fail_threshold: e.target.value })} /></Field></div></fieldset>)}</section>
      <section className="form-section"><div className="section-heading"><h3>一票否决项</h3><button type="button" className="secondary" onClick={() => setProposal(p => ({ ...p, vetoes: [...p.vetoes, { reason: '', confirmed: false, evidence_ids: [] }] }))}>添加否决项</button></div><p className="section-description">只有已确认且有核验证据支持的否决事实才会触发C级；未确认的风险会限制评级上限。</p>{proposal.vetoes.length === 0 && <p>当前没有提出一票否决项。</p>}{proposal.vetoes.map((v, i) => <fieldset className="assumption-editor" key={i}><legend>否决项 {i + 1}</legend><Field label="否决事实与原因"><textarea required rows={2} value={v.reason} onChange={e => setProposal(p => ({ ...p, vetoes: p.vetoes.map((item, index) => index === i ? { ...item, reason: e.target.value } : item) }))} /></Field><Field label="支持否决事实的证据"><ReferenceSelect ids={v.evidence_ids} evidence={detail.evidence} onChange={evidence_ids => setProposal(p => ({ ...p, vetoes: p.vetoes.map((item, index) => index === i ? { ...item, evidence_ids } : item) }))} /></Field><label className="checkbox"><input type="checkbox" checked={v.confirmed} onChange={e => setProposal(p => ({ ...p, vetoes: p.vetoes.map((item, index) => index === i ? { ...item, confirmed: e.target.checked } : item) }))} />已核实这项事实构成无法解决的否决条件</label><button type="button" className="secondary" onClick={() => setProposal(p => ({ ...p, vetoes: p.vetoes.filter((_, index) => index !== i) }))}>移除此否决项</button></fieldset>)}</section>
      <section className="form-section"><h3>正反方与评级限制</h3><div className="form-grid"><Field label="支持理由，每行一条，至少3条"><textarea rows={4} value={proposal.pros.join('\n')} onChange={e => setProposal(p => ({ ...p, pros: e.target.value.split('\n') }))} /></Field><Field label="反对理由，每行一条，至少3条"><textarea rows={4} value={proposal.cons.join('\n')} onChange={e => setProposal(p => ({ ...p, cons: e.target.value.split('\n') }))} /></Field></div><Field label="B级封顶原因，每行一条" hint="如核心价值从未真实验证、老板是唯一关键人、重资产投入后才能测试。没有已知触发项时留空。"><textarea rows={3} value={proposal.policy_caps.join('\n')} onChange={e => setProposal(p => ({ ...p, policy_caps: e.target.value ? e.target.value.split('\n') : [] }))} /></Field><h4>S级额外条件</h4>{[['repeatable', '可复制性与重复验证已确认'], ['resources_available', '公司确实能够投入所需核心资源'], ['portfolio_feasible', '与现有项目的机会成本及资源组合合理'], ['review_complete', '已完成反方审查并反映到以上事实与判断']].map(([key, label]) => <label className="checkbox" key={key}><input type="checkbox" checked={proposal.s_conditions[key] === true} onChange={e => setProposal(p => ({ ...p, s_conditions: { ...p.s_conditions, [key]: e.target.checked } }))} />{label}</label>)}<div className="review-confirm"><label className="checkbox"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} required />我已核对以上事实、证据与判断，确认用于本次评级</label><button className="primary" disabled={busy || !confirmed || pendingFacts} type="submit">确认并计算评级<ArrowUpRight size={16} /></button></div></section>
    </form>}
  </section>;
}
